openapi: 3.2.0
info:
  description: 'The Grafana backend exposes an HTTP API, the same API is used by the frontend to do

    everything from saving dashboards, creating users and updating data sources.'
  title: Grafana HTTP API. SSO Settings API
  contact:
    name: Grafana Labs
    url: https://grafana.com
    email: hello@grafana.com
  version: 0.0.1
servers:
- url: /api
security:
- basic: []
- api_key: []
tags:
- name: sso_settings
paths:
  /v1/sso-settings:
    get:
      description: You need to have a permission with action `settings:read` with scope `settings:auth.:*`.
      tags:
      - sso_settings
      summary: List all SSO Settings entries
      operationId: listAllProvidersSettings
      responses:
        '200':
          $ref: '#/components/responses/listSSOSettingsResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorisedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
  /v1/sso-settings/{key}:
    get:
      description: You need to have a permission with action `settings:read` with scope `settings:auth.:*`.
      tags:
      - sso_settings
      summary: Get an SSO Settings entry by Key
      operationId: getProviderSettings
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/getSSOSettingsResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorisedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
    put:
      description: 'Inserts or updates the SSO Settings for a provider.


        You need to have a permission with action `settings:write` and scope `settings:auth.:*`.'
      tags:
      - sso_settings
      summary: Update SSO Settings
      operationId: updateProviderSettings
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/okResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorisedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '500':
          $ref: '#/components/responses/internalServerError'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                provider:
                  type: string
                settings:
                  type: object
                  additionalProperties: {}
        required: true
    delete:
      description: 'Removes the SSO Settings for a provider.


        You need to have a permission with action `settings:write` and scope `settings:auth.:*`.'
      tags:
      - sso_settings
      summary: Remove SSO Settings
      operationId: removeProviderSettings
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/okResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorisedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '404':
          $ref: '#/components/responses/notFoundError'
        '500':
          $ref: '#/components/responses/internalServerError'
    patch:
      description: 'Partially updates the SSO Settings for a provider. Only provided fields are updated.


        You need to have a permission with action `settings:write` and scope `settings:auth.:*`.'
      tags:
      - sso_settings
      summary: Patch SSO Settings
      operationId: patchProviderSettings
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          $ref: '#/components/responses/okResponse'
        '400':
          $ref: '#/components/responses/badRequestError'
        '401':
          $ref: '#/components/responses/unauthorisedError'
        '403':
          $ref: '#/components/responses/forbiddenError'
        '500':
          $ref: '#/components/responses/internalServerError'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                settings:
                  type: object
                  additionalProperties: {}
        required: true
components:
  responses:
    unauthorisedError:
      description: UnauthorizedError is returned when the request is not authenticated.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
    internalServerError:
      description: InternalServerError is a general error indicating something went wrong internally.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
    notFoundError:
      description: NotFoundError is returned when the requested resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
    listSSOSettingsResponse:
      description: (empty)
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                provider:
                  type: string
                settings:
                  type: object
                  additionalProperties: {}
                source:
                  type: string
    getSSOSettingsResponse:
      description: (empty)
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              provider:
                type: string
              settings:
                type: object
                additionalProperties: {}
              source:
                type: string
    badRequestError:
      description: BadRequestError is returned when the request is invalid and it cannot be processed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
    okResponse:
      description: An OKResponse is returned if the request was successful.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessResponseBody'
    forbiddenError:
      description: ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
  schemas:
    ErrorResponseBody:
      type: object
      required:
      - message
      properties:
        error:
          description: Error An optional detailed description of the actual error. Only included if running in developer mode.
          type: string
        message:
          description: a human readable version of the error
          type: string
        status:
          description: 'Status An optional status to denote the cause of the error.


            For example, a 412 Precondition Failed error may include additional information of why that error happened.'
          type: string
    SuccessResponseBody:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    basic:
      type: http
      scheme: basic
